spring:
  application:
    name: security

  # Configurazione Database
  datasource:
    url: jdbc:mysql://localhost:3306/security?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configurazione JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Configurazione JWT (Proprietà Custom)
jwt:
  secret: mysupersecretkey1234567890abcdef
  expiration: 86400000 # 1 giorno in millisecondi