spring:
  application:
    name: final_project
  config:
    import: optional:file:.env[.properties]

  # Configurazione Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${MAIL_USERNAME}"
    password: "${MAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Configurazione Database
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configurazione JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


# Configurazione JWT (Proprietà Custom)
jwt:
  secret: "${JWT_SECRET}"
  expiration: "${JWT_EXPIRATION}"


# Configurazione PayPal
paypal:
  client-id: "${PAYPAL_CLIENT_ID}"
  client-secret: "${PAYPAL_CLIENT_SECRET}"
  mode: "${PAYPAL_MODE}"
  currency: EUR
  return-url: http://localhost:8080/payment/success
  cancel-url: http://localhost:8080/payment/cancel